services:
  gotemp:
    container_name: gotemp
    image: gotemp
    build:
      context: ./
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    restart: unless-stopped
